server:
  port: 9007
spring:
  application:
    name: dym-sms
  rabbitmq:
    host: 192.168.100.101
    port: 5672
    username: guest
    password: guest
sms:
  appcode: 84ec41cc7a5d47cb807792825bfe0fe5  #使用自己的AppCode
  tpl_id: TP1711063    # 默认模板
