spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': #匹配所有请求
            allowedOrigins: "*" #跨域处理允许所有的域
            allowedMethods: #支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: dongyimai_user_route
          uri: lb://dym-user
          predicates:
            - Path=/api/user/**,/api/address/**,/api/areas/**,/api/cities/**,/api/provinces/**
          filters:
            - StripPrefix=1
        - id: dongyimai_order_route
          uri: lb://dym-order
          predicates:
            - Path=/api/cart/**,/api/order/**,/api/orderItem/**
          filters:
            - StripPrefix=1
        - id: dongyimai_goods
          uri: lb://dym-sellergoods
          predicates:
            - Path=/api/brand/**,/api/goods/**
          filters:
            - StripPrefix=1
        - id: dongyimai_pay
          uri: lb://dym-pay
          predicates:
            - Path=/api/pay/**
          filters:
            - StripPrefix=1
        - id: dongyimai_seckill
          uri: lb://dym-seckill
          predicates:
            - Path=/api/seckillGoods/**,/api/seckillOrder/**
          filters:
            - StripPrefix=1
        - id: user-auth
          uri: lb://user-auth
          predicates:
            - Path=/user/**
server:
  port: 8001
eureka:
  instance:
    # 使用 ip 代替实例名
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka








