server:
  port: 9006
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
spring:
  thymeleaf:
    cache: false
  application:
    name: dym-itempage
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com:
      ujiuye: debug

# 生成静态页的位置
pagepath: d:/items/
